---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: libstore-deploy
  labels:
    app: libstore
spec:
  minReadySeconds: 5
  replicas: 1
  selector: 
    matchLabels:
      app: libstore 
  template:
    metadata:
      labels:
        app: libstore
    spec:
      containers:
        - name: libstore-c
          image: redfiree/libstore:1.0
          envFrom:
            - secretRef:
                name: libstore-deploy-Secret
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 128M 
              cpu: 250m
            limits:
              memory: 500M 
              cpu: 500m  

---
apiVersion: v1 
kind: Service
metadata:
  name: libstore-svc 
spec:
  type: NodePort  #while using cloud you should give Loadbalancer instead of NodePort
  selector: 
    app: libstore
  ports: 
    - port: 80
      targetPort: 3000