---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: booksdb-sts
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      db: books 
  template:
    metadata:
      labels:
        db: books
    spec:
      containers:
        - name: booksdb-c
          image: 
          ports:
            - containerPort: 
          resources: 
            requests:
              memory: 128M
              cpu: 150m 
            limits: 
              memory: 256M
              cpu: 250m 
          volumeMounts:
            - name: 
              mountPath: /var/lib/postgresql/data
              

