---
apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: web-deploy
  annotations: 
     kubernetes.io/change-cause: "version v1.0"
spec:
  minReadySeconds: 10
  replicas: 4
  selector:
    matchLabels:
      app: web 
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata:
      labels:
        app: web
        version: v1.0
    spec: 
      containers: 
        - name: web-c 
          image: redfiree/deploy_slash_test:1.0
          resources:
            requests:
              memory: 128Mi
              cpu: 150m
            limits: 
              memory: 256Mi
              cpu: 400m
          ports: 
            - name: web-p 
              containerPort: 80

--- 
# exposed outside the world to ur application
apiVersion: v1 
kind: Service 
metadata:
  name: web-svc 
spec:
  type: NodePort
  selector:
    app: web 
  ports: 
    - port: 80
      targetPort: 8080

---
#internal application
apiVersion: v1 
kind: Service
metadata:
  name: web-svc 
spec: 
  type: ClusterIP
  selector:
    app: web 
  ports: 
    - name: web-p 
      port: 80
      targetPort: 80



---