---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-pod
      image: nginx 
      ports:
        - name: nginx-c
          containerPort: 80
          protocol: "TCP"