---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: apps-deploy
  annotations:
    kubernetes.io/change-cause: "version v1.0"
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels: 
      app: web
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata: 
      labels:
        app: web 
        version: v1.0 
    spec:
      containers:
        - name: web    
          image: redfiree/deploy_slash_test:1.0 
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 64Mi
              cpu: 125m
            limits:
              memory: 256Mi
              cpu: 250m 

---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: NodePort
  selector:
    app: web 
  ports:
  - port: 80
    targetPort: 80