---
apiVersion: v1
kind: ConfigMap
metadata:
  name: books-db-config
data: 
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: booksdb 
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-db-config
data:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: userdb

---
apiVersion: v1 
kind: ConfigMap
metadata:
  name: user-service-config
data: 
  DATABASE_URL: "postgresql://user:password@userdb-svc:5432/userdb" 
  SECRET_KEY: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"

--- 
apiVersion: v1 
kind: ConfigMap
metadata:
  name: books-service-config
data:
  DATABASE_URL: "postgresql://user:password@booksdb-svc:5432/booksdb"
  SECRET_KEY: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"
    
---
apiVersion: v1 
kind: ConfigMap
metadata: 
  name: libstore-config
data: 
  REACT_APP_BACKEND_API_URL: http://userservice-svc:8000/api/v1
  REACT_APP_BOOKS_API_URL: http://booksservice-svc:8000/api/v1/books
  REACT_APP_USERS_API_URL: http://userservice-svc:8000/api/v1/users




  
