---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: booksdb-rs
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      db: books
  template:
    metadata:
      labels:
       db: books 
    spec: 
      containers: 
        - name: booksdb-c
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: booksdb 
          ports:
            - name: booksdb-p
              containerPort: 5432
          resources:
            requests: 
              memory: 128M
              cpu: 125m
            limits:
              memory: 250M 
              cpu: 250m 

---
apiVersion: v1 
kind: Service
metadata: 
  name: booksdb-svc
spec: 
  type: ClusterIP
  selector: 
    db: books
  ports:
    - port: 5432
      targetPort: 5432


---
apiVersion: apps/v1
kind: ReplicaSet 
metadata:
  name: booksdb-rs
spec:
  minReadySeconds: 15
  replicas: 2
  selector:
    matchLabels: 
      db: books 
  template:
    metadata: 
      labels: 
       db: books 
    spec:
      containers:
        - name: booksdb-c
          image: postgres:15-alpine
          ports: 
            - name: booksdb-p
              containerPort: 5432
          resources:
            requests:   
              memory: "128Mi"
              cpu: "125m" 
            limits:
              memory: "256M"
              cpu: "250m"
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: booksdb

---
apiVersion: v1 
kind: Service
metadata:
  name: booksdb-svc 
spec:
  type: ClusterIP
  selector:
    db: books 
  ports: 
    - name: booksdb-p
      port: 5432
      targetPort: 5432 



