---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: usersdb-rs
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      db: users
  template:
    metadata:
      labels:
       db: users 
    spec: 
      containers: 
        - name: usersdb-c
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: usersdb 
          ports:
            - name: usersdb-p
              containerPort: 5432
          resources:
            requests: 
              memory: 128M
              cpu: 125m
            limits:
              memory: 250M 
              cpu: 250m 

---
apiVersion: v1 
kind: Service
metadata: 
  name: usersdb-svc
spec: 
  type: ClusterIP
  selector: 
    db: users
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: userdb-rs 
spec: 
  minReadySeconds: 15
  replicas: 2 
  selector:
    matchLabels:
      db: users
  template:
    metadata:
      labels:
        db: users
    spec:
      containers:
        - name: usersdb-c 
          image: postgres:15-alpine
          env: 
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: usersdb
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "250m" 
          ports:
            - name: usersdb-p 
              containerPort: 5432

---
apiVersion: v1 
kind: Service 
metadata:
  name: usersdb-svc 
spec:
  type: ClusterIP
  selector: 
    db: users
  ports: 
    - name: usersdb-p 
      port: 5432
      targetPort: 5432 

          