---
apiVersion: v1 
kind: Pod 
metadata:
  name: mysql 
spec:
  containers:
    - name: mysql
      image: mysql:9 
      ports: 
        - containerPort: 3306 
      resources:
        requests:
          memory: 128Mi 
          cpu: 250m 
        limits:
          memory: 512Mi
          cpu: 1000m 
      envFrom: 
        - secretRef:
            name: pv-secret
      volumeMounts:
        - name: libdb
          mountPath: /var/lib/mysql 
  volumes: 
    - name: libdb 
      persistentVolumeClaim:
        claimName: mysql-pvc
      
      



